create table CONFIGURACAO(
	HOSTNAME VARCHAR(30),
	QTDE_RAM VARCHAR(30),
	TAM_MAX_ARQ_RAM VARCHAR(30),
	TAM_MAX_ARQ_DISCO VARCHAR(30),
	TAM_MIN_ARQ_DISCO VARCHAR(30),
	PERC_MIN_CACHE_SWAP VARCHAR(30),
	PERC_MAX_CACHE_SWAP VARCHAR(30),
	TAM_ARQUIVO_CACHE VARCHAR(30), 
	QTDE_PASTAS VARCHAR(30), 
	QTDE_SUB_PASTAS VARCHAR(30)
);


CREATE TABLE BLOQUEIO(
	SITES_LIBERADOS TEXT,
	EXT_BLOQUEADOS VARCHAR(50),
	BLOQUEADOS_POR_IP TEXT,
	HORA_INICIAL VARCHAR(10),
	HORA_FINAL VARCHAR(10),
	POR_HORA VARCHAR(1),
	USUARIO VARCHAR(30),
	SENHA VARCHAR(30),
	FG_POR_HORA VARCHAR(1),
	FG_POR_EXTENSAO VARCHAR(1),
	FG_POR_AUTENTICACAO VARCHAR(1)
);